/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.recordlog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DLRecordLog service. Represents a row in the &quot;dlrecordlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.documentlibrary.recordlog.model.impl.DLRecordLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.documentlibrary.recordlog.model.impl.DLRecordLogImpl}.
 * </p>
 *
 * @author Jitendra Rajput
 * @see DLRecordLog
 * @see com.liferay.portlet.documentlibrary.recordlog.model.impl.DLRecordLogImpl
 * @see com.liferay.portlet.documentlibrary.recordlog.model.impl.DLRecordLogModelImpl
 * @generated
 */
public interface DLRecordLogModel extends BaseModel<DLRecordLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a d l record log model instance should use the {@link DLRecordLog} interface instead.
	 */

	/**
	 * Returns the primary key of this d l record log.
	 *
	 * @return the primary key of this d l record log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this d l record log.
	 *
	 * @param primaryKey the primary key of this d l record log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log ID of this d l record log.
	 *
	 * @return the log ID of this d l record log
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this d l record log.
	 *
	 * @param logId the log ID of this d l record log
	 */
	public void setLogId(long logId);

	/**
	 * Returns the file entry ID of this d l record log.
	 *
	 * @return the file entry ID of this d l record log
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this d l record log.
	 *
	 * @param fileEntryId the file entry ID of this d l record log
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the company ID of this d l record log.
	 *
	 * @return the company ID of this d l record log
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this d l record log.
	 *
	 * @param companyId the company ID of this d l record log
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this d l record log.
	 *
	 * @return the user ID of this d l record log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this d l record log.
	 *
	 * @param userId the user ID of this d l record log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this d l record log.
	 *
	 * @return the user uuid of this d l record log
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this d l record log.
	 *
	 * @param userUuid the user uuid of this d l record log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this d l record log.
	 *
	 * @return the user name of this d l record log
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this d l record log.
	 *
	 * @param userName the user name of this d l record log
	 */
	public void setUserName(String userName);

	/**
	 * Returns the ip address of this d l record log.
	 *
	 * @return the ip address of this d l record log
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this d l record log.
	 *
	 * @param ipAddress the ip address of this d l record log
	 */
	public void setIpAddress(String ipAddress);

	/**
	 * Returns the create date of this d l record log.
	 *
	 * @return the create date of this d l record log
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this d l record log.
	 *
	 * @param createDate the create date of this d l record log
	 */
	public void setCreateDate(Date createDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DLRecordLog dlRecordLog);

	public int hashCode();

	public CacheModel<DLRecordLog> toCacheModel();

	public DLRecordLog toEscapedModel();

	public String toString();

	public String toXmlString();
}