/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.recordlog.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog;
import com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLogModel;
import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DLRecordLog service. Represents a row in the &quot;dlrecordlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLogModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DLRecordLogImpl}.
 * </p>
 *
 * @author Jitendra Rajput
 * @see DLRecordLogImpl
 * @see com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog
 * @see com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLogModel
 * @generated
 */
public class DLRecordLogModelImpl extends BaseModelImpl<DLRecordLog>
	implements DLRecordLogModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a d l record log model instance should use the {@link com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog} interface instead.
	 */
	public static final String TABLE_NAME = "dlrecordlog";
	public static final Object[][] TABLE_COLUMNS = {
			{ "logId", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "ipAddress", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table dlrecordlog (logId LONG not null primary key,fileEntryId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,ipAddress VARCHAR(75) null,createDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table dlrecordlog";
	public static final String ORDER_BY_JPQL = " ORDER BY dlRecordLog.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY dlrecordlog.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog"),
			true);
	public static long FILEENTRYID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog"));

	public DLRecordLogModelImpl() {
	}

	public long getPrimaryKey() {
		return _logId;
	}

	public void setPrimaryKey(long primaryKey) {
		setLogId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_logId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DLRecordLog.class;
	}

	public String getModelClassName() {
		return DLRecordLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("logId", getLogId());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("ipAddress", getIpAddress());
		attributes.put("createDate", getCreateDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long logId = (Long)attributes.get("logId");

		if (logId != null) {
			setLogId(logId);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		String ipAddress = (String)attributes.get("ipAddress");

		if (ipAddress != null) {
			setIpAddress(ipAddress);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	public long getLogId() {
		return _logId;
	}

	public void setLogId(long logId) {
		_logId = logId;
	}

	public long getFileEntryId() {
		return _fileEntryId;
	}

	public void setFileEntryId(long fileEntryId) {
		_columnBitmask |= FILEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFileEntryId) {
			_setOriginalFileEntryId = true;

			_originalFileEntryId = _fileEntryId;
		}

		_fileEntryId = fileEntryId;
	}

	public long getOriginalFileEntryId() {
		return _originalFileEntryId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	public String getIpAddress() {
		if (_ipAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _ipAddress;
		}
	}

	public void setIpAddress(String ipAddress) {
		_ipAddress = ipAddress;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DLRecordLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DLRecordLog toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DLRecordLog)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		DLRecordLogImpl dlRecordLogImpl = new DLRecordLogImpl();

		dlRecordLogImpl.setLogId(getLogId());
		dlRecordLogImpl.setFileEntryId(getFileEntryId());
		dlRecordLogImpl.setCompanyId(getCompanyId());
		dlRecordLogImpl.setUserId(getUserId());
		dlRecordLogImpl.setUserName(getUserName());
		dlRecordLogImpl.setIpAddress(getIpAddress());
		dlRecordLogImpl.setCreateDate(getCreateDate());

		dlRecordLogImpl.resetOriginalValues();

		return dlRecordLogImpl;
	}

	public int compareTo(DLRecordLog dlRecordLog) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), dlRecordLog.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DLRecordLog dlRecordLog = null;

		try {
			dlRecordLog = (DLRecordLog)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = dlRecordLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DLRecordLogModelImpl dlRecordLogModelImpl = this;

		dlRecordLogModelImpl._originalFileEntryId = dlRecordLogModelImpl._fileEntryId;

		dlRecordLogModelImpl._setOriginalFileEntryId = false;

		dlRecordLogModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DLRecordLog> toCacheModel() {
		DLRecordLogCacheModel dlRecordLogCacheModel = new DLRecordLogCacheModel();

		dlRecordLogCacheModel.logId = getLogId();

		dlRecordLogCacheModel.fileEntryId = getFileEntryId();

		dlRecordLogCacheModel.companyId = getCompanyId();

		dlRecordLogCacheModel.userId = getUserId();

		dlRecordLogCacheModel.userName = getUserName();

		String userName = dlRecordLogCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dlRecordLogCacheModel.userName = null;
		}

		dlRecordLogCacheModel.ipAddress = getIpAddress();

		String ipAddress = dlRecordLogCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			dlRecordLogCacheModel.ipAddress = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dlRecordLogCacheModel.createDate = createDate.getTime();
		}
		else {
			dlRecordLogCacheModel.createDate = Long.MIN_VALUE;
		}

		return dlRecordLogCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{logId=");
		sb.append(getLogId());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", ipAddress=");
		sb.append(getIpAddress());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.portlet.documentlibrary.recordlog.model.DLRecordLog");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>logId</column-name><column-value><![CDATA[");
		sb.append(getLogId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ipAddress</column-name><column-value><![CDATA[");
		sb.append(getIpAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DLRecordLog.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DLRecordLog.class
		};
	private long _logId;
	private long _fileEntryId;
	private long _originalFileEntryId;
	private boolean _setOriginalFileEntryId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private String _ipAddress;
	private Date _createDate;
	private long _columnBitmask;
	private DLRecordLog _escapedModelProxy;
}